### ISSUE TITLE
JSON errors with valid JSON

### ISSUE THREAD

**Issue by harrypropellernet** [pydata/pandas-gbq#110]
Hi there,

To preface this, the code works perfectly as expected on a windows machine, however when run on a linux machine I am encountering the following error.

when attempting to upload a dataframe from pandas to GBQ I encounter:
```
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1.
```
I've searched through the code and extracted the json that it is sending to GBQ and the json is valid,

```
{"Mobile":"100.00%","Channelgrouping":"Organic Search","Date":"2017-12-26","Date4weeksago":"2017-11-28","Devicecategory":"mobile","Goal7completions":180,"Goal7completionsLastYear":0,"Goal7completionsLastYearMobileAdjustment":0,"Goal7completionsMobileAdjustment":180,"MobileAdjustment":1.0,"Month":12,"Newusers":"31,095","NewusersLastYear":0,"NewusersLastYearMobileAdjustment":0,"NewusersMobileAdjustment":"31,095","Period":11,"SEORevenueContribPast4Weeks":"0.00%","SEORevenueContribThisWeek":"39.90%","SEOSessionsContribPast4Weeks":"0.00%","SEOSessionsContribPastWeek":"54.04%","Sessions":"64,848","SessionsLastYear":0,"SessionsLastYearMobileAdjustment":0,"SessionsMobileAdjustment":"64,848","Transactionrevenue":"16,106","TransactionrevenueLastYear":0,"TransactionrevenueLastYearMobileAdjustment":0,"TransactionrevenueMobileAdjustment":"16,106","Transactions":179,"TransactionsLastYear":0,"TransactionsLastYearMobileAdjustment":0,"TransactionsMobileAdjustment":179,"WeekSunSat":52,"Year":2017}
```

I've also tried all the to_json orient methods e.g. split index etc.

Is this a known issue?

full traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 592, in load_data
    job_config=job_config).result()
  File "/usr/local/lib/python3.6/site-packages/google/cloud/bigquery/job.py", line 528, in result
    return super(_AsyncJob, self).result(timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/google/api_core/future/polling.py", line 111, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "WaitroseMain.py", line 133, in <module>
    load = Waitrose.load(df)
  File "WaitroseMain.py", line 114, in load
    uploader.update(client, dataframes['gad'],'WaitroseAuto.gad')
  File "/home/harry/Automation/ReportingAutomation/DataStorage/BigQueryTools.py", line 155, in update
    pd.DataFrame.to_gbq(dataframe, destination_table=destination_table, project_id='joe-python-analytics', chunksize=5000, if_exists='append')
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 1060, in to_gbq
    if_exists=if_exists, private_key=private_key)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/gbq.py", line 108, in to_gbq
    if_exists=if_exists, private_key=private_key)
  File "/usr/local/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 990, in to_gbq
    connector.load_data(dataframe, dataset_id, table_id, chunksize)
  File "/usr/local/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 594, in load_data
    self.process_http_error(ex)
  File "/usr/local/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 456, in process_http_error
    raise GenericGBQException("Reason: {0}".format(ex))
pandas_gbq.gbq.GenericGBQException: Reason: 400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1.
```

**Comment by maxim-lian** [comment]
Thanks for the report. It's very close to being a reproducible error - could you put it over the line so it's reproducible?

Also you can use ``` to mark code / output sections

**Comment by harrypropellernet** [comment]
On further investigation the following json works:

```
{"BounceRagePerc":0.0,"Bouncerate":0,"BouncerateLastYear":0,"Date":42484,"Goal7completions":0,"Goal7completionsLastYear":0,"Itemquantity":0,"ItemquantityLastYear":0,"Itemrevenue":0,"ItemrevenueLastYear":0,"Newsessions":0,"NewsessionsLastYear":0,"Newusers":0,"NewusersLastYear":0,"Pageviews":0,"PageviewsLastYear":0,"Segment":"Waitrose - Products","Sessions":0,"SessionsLastYear":0,"Totaltimeonsitehours":0,"TotaltimeonsitehoursLastYear":0,"WeekSunSat":18,"Year":2016}
```

but the previous json will always return the error:

```
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1.
```

apologies, but I am unsure how to make it more reproducible?

**Comment by maxim-lian** [comment]
Thanks @harrypropellernet 

To make reproducible, post some code that someone can copy & paste to get the error. 

Can you also find the difference between the JSON that works and the JSON that doesn't, so the error is from a small sample?

**Comment by harrypropellernet** [comment]
So I managed to fix it, It wasnt an error with pandas, however it was rather difficult to decipher the problem from the error messages. extra incomplte rows at the bottom of the dataframe, and some issues with the #NA cells that excel uses
