### ISSUE TITLE
`read_gbq` fails with ValueError when a column is of type `TIME`

### ISSUE THREAD

**Issue by german1608** [pydata/pandas-gbq#328]
I believe that the smallest example to reproduce this is by running:

```python
from pandas_gbq import read_gbq

read_gbq('select current_time()')
```

the traceback is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 967, in read_gbq
    progress_bar_type=progress_bar_type,
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 532, in run_query
    progress_bar_type=progress_bar_type,
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/pandas_gbq/gbq.py", line 562, in _download_results
    progress_bar_type=progress_bar_type,
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 1776, in to_dataframe
    for frame in self.to_dataframe_iterable(dtypes=dtypes):
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/google/cloud/bigquery/table.py", line 1439, in _to_page_iterable
    for item in tabledata_list_download():
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 565, in download_dataframe_tabledata_list
    yield _tabledata_list_page_to_dataframe(page, column_names, dtypes)
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 539, in _tabledata_list_page_to_dataframe
    columns[column_name] = pandas.Series(page._columns[column_index], dtype=dtype)
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/pandas/core/series.py", line 327, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/pandas/core/construction.py", line 447, in sanitize_array
    subarr = _try_cast(data, dtype, copy, raise_cast_failure)
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/pandas/core/construction.py", line 568, in _try_cast
    subarr = construct_1d_ndarray_preserving_na(subarr, dtype, copy=copy)
  File "/home/german/Documents/c4v/infra-tools/probe-analyzer/env/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 1618, in construct_1d_ndarray_preserving_na
    subarr = np.array(values, dtype=dtype, copy=copy)
```

I believe that changing the mapping between the `TIME` data-type and its `dtype` to `object` can fix the issue:

https://github.com/pydata/pandas-gbq/blob/d251db03b159447331ac9ae63e13d295d75bad70/pandas_gbq/gbq.py#L698-L710

... but haven't tried yet and I have never collaborated to this repository before.

Any other idea to solve this issue?

**Comment by german1608** [comment]
My intuition for using `object` instead of `datetime64[ns]` is because the Google BigQuery client returns `object` when calling `to_dataframe`:

```python
>>> df = client.query('select current_time()').result().to_dataframe()
>>> df
               f0_
0  20:50:30.587672
>>> df.dtypes
f0_    object
dtype: object
```

**Comment by tswast** [comment]
I believe `to_dataframe` takes a `dtypes` dictionary. Can we check if it's able to use this?

P.S. I wonder if this started failing recently or if it was always the case that TIME columns were not supported?

**Comment by tswast** [comment]
Oh, and thanks for the reproducible test case!

**Comment by german1608** [comment]
> I believe `to_dataframe` takes a `dtypes` dictionary. Can we check if it's able to use this?

Indeed it does, and that triggers the same error if one uses the following `dtypes`:

```python
{
  "col_name": "datetime64[ns]"
}
```

I could try to make a PR to fix this if you don't mind!

**Comment by tswast** [comment]
Thanks for checking. Yes, a PR would be very welcome.

**Comment by tswast** [comment]
I'm having a bit of a hard time reproducing, but it does appear from the code that this error would occur. Not sure why it isn't failing in my case. Maybe it depends on `google-cloud-bigquery` version? I have

```
$ conda list | grep bigquery
google-cloud-bigquery     2.1.0              pyhc8dfbb8_0    conda-forge
google-cloud-bigquery-core 2.1.0              pyhc8dfbb8_0    conda-forge
google-cloud-bigquery-storage 2.0.0                    pypi_0    pypi
google-cloud-bigquery-storage-core 2.0.0              pyh9f0ad1d_1    conda-forge
```

**Comment by tswast** [comment]
I just stepped through the code, and https://github.com/googleapis/python-bigquery/blob/0c387dadd57fba9cdbfd39abe530de209943db9a/google/cloud/bigquery/table.py#L1721 isn't failing on my machine, but it's also not trying to convert from `object` to `datetime64[ns]` despite being passed that as a dtype.
