### ISSUE TITLE
BUG:AttributeError when TIMESTAMP data Exceed "2262-04-11 23:47:16"

### ISSUE THREAD

**Issue by uniocto** [pydata/pandas-gbq#352]
I found AttributeError when TIMESTAMP data Exceed "2262-04-11 23:47:16".
```
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
>>> import pandas as pd
>>> import pandas_gbq
>>> pandas_gbq.__version__
'0.14.1'
>>> print(pd.read_gbq(project_id="hogehoge", query='SELECT TIMESTAMP("2262-04-11 23:47:16")'))
            f0_
0 2262-04-11 23:47:16+00:00
>>> print(pd.read_gbq(project_id="hogehoge", query='SELECT TIMESTAMP("2262-04-11 23:47:17")'))
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "~\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\io\gbq.py", line 184, in read_gbq
  return pandas_gbq.read_gbq(
 File "~\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas_gbq\gbq.py", line 976, in read_gbq
  final_df = connector.run_query(
 File "~\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas_gbq\gbq.py", line 532, in run_query
  return self._download_results(
 File "~\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas_gbq\gbq.py", line 603, in _download_results
  df = pandas_gbq.timestamp.localize_df(df, schema_fields)
 File "~\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas_gbq\timestamp.py", line 39, in localize_df
  if field["type"].upper() == "TIMESTAMP" and df[column].dt.tz is None:
 File "~\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\generic.py", line 5137, in __getattr__
  return object.__getattribute__(self, name)
 File "~\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\accessor.py", line 187, in __get__
  accessor_obj = self._accessor(obj)
 File "~\AppData\Local\Programs\Python\Python38\lib\site-packages\pandas\core\indexes\accessors.py", line 480, in __new__
  raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values
```
Probably due to the pandas Timestamp limit.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.max.html

**Comment by max-sixty** [comment]
Yes your diagnosis is correct!

**Comment by max-sixty** [comment]
Closing, but reopen if necessary
